### ISSUE TITLE
Deleting a Media does not delete its Files

### ISSUE THREAD

**Issue by emetsger** [jhu-idc/idc-isle-dc#100]
This behavior is documented in the `11-file-deletion-tests` suite, introduced in 501d1d7.

Attempting to delete a Media and its Files from the [Media listing page](https://islandora-idc.traefik.me/admin/content/media) results in a deleted Media, but the Files are left over.

As an admin, create or migrate a Media with a File.  Navigate to the [Media listing page](https://islandora-idc.traefik.me/admin/content/media), and delete the Media and its Files.  Observe that you receive two messages in the flash, one of them being a warning that an item couldn't be deleted.  Navigate to the [File listing page](https://islandora-idc.traefik.me/admin/content/files/) and note that the File is still there, and its bytes can still be downloaded.

This behavior is unexpected, and unexplained.  It only is an issue if we feel the behavior needs to be changed or otherwise explained, otherwise, it is documented in the `11-file-deletion-tests` test suite.

**Comment by bseeger** [comment]
I wonder if it relates to this: https://www.drupal.org/node/2891902 where permanent files are no longer down graded to temporary?  (temporary files are cleaned up at a configurable point in time).

**Comment by bseeger** [comment]
I believe this is resolved because of the fix in the media migration files in the validation PR.  Specifically this change seems to have fixed it: 

https://github.com/jhu-idc/idc-isle-dc/pull/193/files#diff-73de25eb55f4875e835284d2761665d76f1957580d801b29ece086afbc560d93R87

I just did a quick manual test and it shows that the file is gone when I delete the media it was attached to. No error message anymore. 

Test was updated as well, here: https://github.com/jhu-idc/idc-isle-dc/pull/193/files#diff-32f6b408b2b71c8edd0b03d68d98146c43f1d7607efe6cf3da4490b65eb94426

Things look good and I think we can close this ticket, @birkland
