### ISSUE TITLE
Assess impact and need to upgrade to Drupal 9

### ISSUE THREAD

**Issue by birkland** [jhu-idc/idc-isle-dc#71]
Drupal 8 is slated for End of Life in November 2021, so it would be in our best interest to upgrade to Drupal 9 before launch.  Islandora recently [completed a sprint](https://islandora.ca/content/drupal-9-we-did-it) for Drupal 9 compatibility.

In order to do this, we need to:
* Assess impact of upgrading to Drupal 9, if any
* find and remove any non-D9-compatible modules, if any.

**Comment by birkland** [comment]
If the upgrade path is obvious, please do it.  Otherwise, if there are complications (e.g. one of our modules is fundamentally incompatible), please identify the problem areas for further triage

**Comment by jordandukart** [comment]
@birkland, will approach this from a report perspective in mind initially. Given our current Docker inexperience it may make more sense to have iDC staff handle the actual changes (if required) that are found. Will re-evaluate this thought once the dive is complete.

**Comment by birkland** [comment]
It's fine to assess and then check in to see what sort of implementation path is most logical.

**Comment by jordandukart** [comment]
Environment requirements are noted [here](https://www.drupal.org/docs/understanding-drupal/how-drupal-9-was-made-and-what-is-included/environment-requirements-of). The below has been evaluated on a development environment.

* PHP 7.3.27 which is sufficient.
* NGINX version is 1.18 which is sufficient.
* MariaDB version is 10.4.17 where D9 requires 10.3.7+ which is sufficient.
* Drush's version needed to be bumped to ^10 as per [the docs](https://www.drush.org/latest/install/#drupal-compatibility).

While not necessarily constrained for this ticket moving to Composer 2 would probably make sense as it adds major performance improvements. Similarly there are certain "recommended" Drupal projects that aren't being leveraged such as [core-recommended](https://github.com/drupal/core-recommended) and [core-vendor-hardening](https://github.com/drupal/core-vendor-hardening). If core-recommended is not pursued than Drupal core itself and other of its listed dependency will be required to be updated.

Similarly, moving forward running [upgrade_status](https://www.drupal.org/project/upgrade_status) on new modules being introduced or custom code being written will ensure that things are aligned accordingly.

For reference the below table was generated from upgrade-status' [output](https://gist.github.com/jordandukart/f5d9d075ae53de38f4d67e46161ca5ad) for all modules present on a development environment. This lists all modules present and whether they require updates to their versions or additional code changes.

| Module | Notes | Requires Version Bump or Changes |
| --- | --- | --- |
|[Admin Toolbar](https://www.drupal.org/project/admin_toolbar)| Current version supports D9, however is a new major release.| N|
|[Automatic Entity Labels](https://www.drupal.org/project/auto_entitylabel])|Not enabled, could likely be removed from composer.|N|
|[CAPTCHA](https://www.drupal.org/project/captcha)|Up to date|N|
|[Configuration Update Manager](https://www.drupal.org/project/config_update)|Config_update_ui seems to have an outstanding issue with a [Drush deprecation](https://www.drupal.org/project/config_update/issues/3042621). This module is not enabled but noted if there's an intent in the future to leverage it.|N|
|[Contact Ajax](https://www.drupal.org/project/contact_ajax)|Up to date|N|
|[Contact Block](https://www.drupal.org/project/contact_block)|Up to date|N|
|[Contact Emails](https://www.drupal.org/project/contact_emails)|Up to date|N|
|[Contact storage](https://www.drupal.org/project/issues/contact_storage)|Up to date|N|
|[Content browser](https://www.drupal.org/project/content_browser)|Requires an update to pull in D9 compatability. While upgrade-status does complain about deprecations, [a closed issue](https://www.drupal.org/project/content_browser/issues/3042779) states that the libraries deprecation is indeed a false positive.|Y|
|[Context](https://www.drupal.org/project/context)|Up to date|N|
|[Controlled Access Terms](https://github.com/jhu-idc/controlled_access_terms)|Fork of the Islandora module, up to date.|N|
|[Serialization (CSV)](https://www.drupal.org/project/csv_serialization)|Up to date|N|
|[Devel](https://www.drupal.org/project/devel)|Locked on 8.x-2.1 which does not have D9 support.|Y|
|[Embed](https://www.drupal.org/project/embed)|Up to date|N|
|[Entity Browser](https://www.drupal.org/project/entity_browser)|Up to date|N|
|[Entity Embed](https://www.drupal.org/project/entity_embed)|Up to date|N|
|[Entity Reference Unpublished](https://www.drupal.org/project/entity_reference_unpublished)|Up to date|N|
|[Entity Prepopulate](https://www.drupal.org/project/epp)|Up to date|N|
|[Facets](https://www.drupal.org/project/facets)|Up to date|N|
|[Features](https://www.drupal.org/project/features)|Module is up to date, has a deprecation in a test which wouldn't limit this module from being used. AFAICT no issue made to report this on d.o.|N|
|[Field Group](https://www.drupal.org/project/field_group)|Module is up to date, has a deprecation on a core JS library that is removed in D9. This [issue](https://www.drupal.org/project/field_group/issues/3154304) denotes that in [the D9 compatibility issue](https://www.drupal.org/project/field_group/issues/3109552) a dependency on a new module [was added](https://git.drupalcode.org/project/field_group/commit/f6f486e). Not sure if iDC takes advantage of this behavior or not which may require this additional module being added and enabled.|Y|
|[Field Permissions](https://www.drupal.org/project/field_permissions)|Up to date|N|
|[File metadata manager](https://www.drupal.org/project/file_mdm)|Up to date|N|
|[File replace](https://www.drupal.org/project/file_replace)|Up to date|N|
|[File Hash](https://www.drupal.org/project/filehash)|Up to date|N|
|[Flysystem](https://www.drupal.org/project/flysystem)|Up to date|N|
|[Geolocation](https://www.drupal.org/project/geolocation)|Up to date|N|
|[Hook Post Action](https://www.drupal.org/project/hook_post_action)|Didn't have D9 support until [January](https://www.drupal.org/project/hook_post_action/issues/3121662). Decision was made [by Islandora](https://github.com/Islandora/documentation/issues/1731) to remove support for the module because of it. Module is disabled could likely just be removed.|N|
|[iDC Export Module](https://github.com/jhu-idc/idc_export)|Needs core_version_requirement added to make it D9 compatible. Is also a deprecation warning about how the AbstractCsv class is being used.|Y|
|[IDC Migration](https://github.com/jhu-idc/idc_migration)|Needs core_version_requirement added to make it D9 compatible.|Y|
|[iDC UI Module](https://github.com/jhu-idc/idc_ui_module)|Needs core_version_requirement added to make it D9 compatible.|Y|
|[ImageMagick](https://www.drupal.org/project/imagemagick)|[3.2](https://www.drupal.org/project/imagemagick/issues/3206264) drops support for 8.8 and 9.0 proper. Given the version of D9 being installed may want to version bump but wouldn't be required.|N|
|[Islandora](https://github.com/Islandora/islandora)|Locked at a point where there is D9 support.|N|
|[Islandora Defaults](https://github.com/jhu-idc/islandora_defaults)|Since this is a fork the work done in the [D9 sprint](https://github.com/Islandora/islandora_defaults/pull/40/files) is not present. Given that's it's mostly config work odds are a lot of it would not be applicable. However submodule changes and others will require this to be updated.|Y|
|[Islandora Fits](https://github.com/roblib/islandora_fits)|Requires a version bump from the D9 sprint.|Y|
|[JSON-LD](https://github.com/Islandora/jsonld)|Locked at a version that has D9 support.|N|
|[JSON Web Token Authentication (JWT)](https://www.drupal.org/project/jwt)|Up to date|N|
|[Key](https://www.drupal.org/project/key)|Up to date, however there are [open issues](https://www.drupal.org/project/issues/key?categories=All) in regards to D9 compatibility issues. As `key` is leveraged by the `JWT` module above this somewhat of a concern.|N|
|[Libraries](https://www.drupal.org/project/libraries)|Locked version has D9 support, version bump would likely be recommend here as there has been some further deprecation fixes.|Y|
|[Migrate Files (extended)](https://www.drupal.org/project/migrate_file)|Currently locked at 1.1.x requires a version bump to be able to have D9 support.|Y|
|[Migrate Plus](https://www.drupal.org/project/migrate_plus)|Up to date|N|
|[Migrate Source CSV](https://www.drupal.org/project/migrate_source_csv)|Up to date|N|
|[Migrate Source UI](https://www.drupal.org/project/migrate_source_ui)|Up to date|N|
|[Migrate Tools](https://www.drupal.org/project/migrate_tools)|Up to date|N|
|[OpenSeadragon Viewer](https://github.com/Islandora/openseadragon)|Locked at a version that has D9 support.|N|
|[Pager Serializer](https://www.drupal.org/project/pager_serializer)|Up to date|N|
|[PDF](https://www.drupal.org/project/pdf)|Locked version has support for D9.|N|
|[Permissions by Term](https://www.drupal.org/project/permissions_by_term)|D9 support added in [this issue](https://www.drupal.org/project/permissions_by_term/issues/3136115). Would require a version bump, however this module is disabled. If it's not being leveraged perhaps it should be removed.|?|
|[Prepopulate](https://www.drupal.org/project/prepopulate)|Up to date|N|
|[RDF UI](https://www.drupal.org/project/rdfui)|Requires a version bump to the latest beta for D9 support.|Y|
|[Reference Value Pair](https://github.com/jhu-idc/reference_value_pair)|No D9 version is available upstream. Their [issue queue](https://www.drupal.org/project/issues/reference_value_pair?categories=All) seems very inactive as there are open D9 tickets. Any D9 compatibility work would need be taken on and pushed to iDC's fork.|Y|
|[REST OAI-PMH](https://www.drupal.org/project/rest_oai_pmh)|Up to date|N|
|[REST UI](https://www.drupal.org/project/restui)|Up to date|N|
|[Role Delegation](https://www.drupal.org/project/role_delegation)|Up to date|N|
|[Role Hierarchy](https://www.drupal.org/project/role_hierarchy)|Up to date|N|
|[S3 File System](https://www.drupal.org/project/s3fs)|Up to date|N|
|[Search API](https://www.drupal.org/project/search_api)|Up to date|N|
|[Search API Solr](https://www.drupal.org/project/search_api_solr)|Up to date|N|
|[SimpleSAMLphp Authentication](https://www.drupal.org/project/simplesamlphp_auth)|Up to date|N|
|[Sophron](https://www.drupal.org/project/sophron)|Up to date|N|
|[Title length](https://www.drupal.org/project/title_length)|Up to date|N|
|[Token](https://www.drupal.org/project/token)|Up to date|N|
|[Transliterate Filenames for Uploads](https://www.drupal.org/project/transliterate_filenames)|Is a [deprecated function](https://git.drupalcode.org/project/transliterate_filenames/-/blob/8.x-1.x/transliterate_filenames.module#L27-29) but is likely mitigated due to the function_exists check|N|
|[Views Data Export](https://www.drupal.org/project/views_data_export)|Up to date|N|
|[Workbench](https://git.drupalcode.org/project/workbench)|Up to date|N|
|[Workbench Access](https://www.drupal.org/project/workbench_access)|Has a deprecation but is a false positive.|N|
|[Carapace](https://github.com/Islandora/carapace)|Up to date|N|
|[JHU IDC UI Theme](https://github.com/jhu-idc/idc-ui-theme)|Requires a core_version_requirement bump.|Y|
|[Crayfish-Commons](https://github.com/Islandora/Crayfish-Commons)|Has the D9 commit.|N|

**Comment by birkland** [comment]
@jordandukart Thanks, this sort of report is exactly what we need.

A few questions:
* As far as [reference_value_pair](https://github.com/jhu-idc/reference_value_pair) is concerned,  I believe it is something Bethany wrote, and is not a fork.  Would this mean that it's in the category of the other jhu modules in that it needs a `core_version_requirement` bump, or is there an actual incompatibility with it?
* For the jhu that require a core_version_requirement bump, is this a trivial fix?
* To my Drupal-untrained eye looks like bringing islandora_defaults in line with D9-compatible upstream is probably the most involved remediation of the bunch (Most of the rest reduce to either version upgrades, or removal).  Would you agree?
* Would you recommend implementing these upgrades and go live with D9 in production before launch?

**Comment by jordandukart** [comment]
- So `reference_value_pair`'s initial commit was essentially [forking from upstream](https://github.com/jhu-idc/reference_value_pair/commit/683fe0c1a44b4af6cbb6f0fba207be8cf58df5c8). If you look at the [output](https://gist.github.com/jordandukart/f5d9d075ae53de38f4d67e46161ca5ad#file-upgrade_status-txt-L2744-L2976) there is a decent amount of deprecated functions that need to be updated and tested. This probably represents the biggest "code" changes that would need to be undertook by iDC for compatability.
- `core_version_requirement` bumping is indeed trivial, [as simple as adding a missing key to the info.yml](https://www.drupal.org/node/3070687).
- Given the forked nature of `islandora_defaults` any pull from upstream would need to be vetted to ensure there would be no stomping over customizations. The nature of [the update](https://github.com/Islandora/islandora_defaults/pull/40/files) is somewhat large but the main pieces would be ensuring that callbacks for fields are not utilizing deprecated functions as well the submodules have their `info.yml`s updated accordingly.
- Given the amount of work here it'd definitely be preferable to have this work undertook before launch. In terms of updating `reference_value_pair` and the other listed things above it's not a whole lot of development time. IMO, the updates to composer proper as well as have these changes reflected within provisioning pose the biggest risk. I'm not familiar with how ISLE handles updates (assuming there are existing boxes that would need to be updated).

**Comment by jordandukart** [comment]
Would note that looking at moving to `core-recommended` would be preferable. Without it it's possible that when doing composer updates, versions of dependencies that have _NOT_ been tested by Drupal for compatibility with core are pulled in.

**Comment by birkland** [comment]
@jordandukart I created a pull request for moving to `core-recommended`: https://github.com/jhu-idc/idc-isle-dc/pull/153 , can you take a look at it and see if it's what you meant?  It looks like there was considerable version drift over time, as most of the dependency updates are downgrades (feel free to look at the bot's comment on that PR highlighting dependency diffs, or glance at composer.lock)

Can you clarify what you think is the biggest risks?  does "updates to composer proper" describe the recommendation for moving to composer 2.0? Likewise, I'm not sure what "having these changes reflected with provisioning" means.  Does that refer to the process of deploying these changes to the cloud instances?

**Comment by jordandukart** [comment]
Will have a look at https://github.com/jhu-idc/idc-isle-dc/pull/153.

> Can you clarify what you think is the biggest risks? does "updates to composer proper" describe the recommendation for moving to composer 2.0? Likewise, I'm not sure what "having these changes reflected with provisioning" means. Does that refer to the process of deploying these changes to the cloud instances?

I was referring to the updates to moving towards `core-recommended` and `core-vendor-hardening` as well as potentially version bumping up to Composer 2 globally.

In regards to "having these changes reflected with provisioning" my intent was to highlight our (dgi's) inexperience with the build pipeline that exists at iDC. More so, if we were to take on doing the Composer based updates as opposed to say the code updation that there could be some time lost to becoming familiar/comfortable with that process.

Lastly, when we make changes such in our provisioning (puppet based) we have to account for and test for updating an existing, running box as opposed to fresh installs. I'm not certain of the current landscape at iDC and whether that is a concern at this time.

**Comment by birkland** [comment]
I see, thanks for the clarification.  For us, _most_ of the work related to updating composer.json/composer.lock is fighting composer itself, as it is difficult to reason about the scope of changes it'll apply.  That's just plain vanilla composer.  I'm sure anybody on your team could do it, if the need came up.  Once committed, CI will take care of the rest.  Generally speaking, the development environment (and CI tests) always start from a known state known as a "snapshot" which is essentially a "backup" of all persistent state (databases, SOLR, persistent volumes) from a known and controlled point-in-time.  Docker magic just makes the "restore from snapshot" step essentially instantaneous.   Thus, we rarely/never do installs from scratch.  One of our goals in that regard was being able to observe/test/verify the actions of module hooks (e.g. an upgraded module version results in a new hook firing, which may modify database state) in the development and CI, before "potentially dangerous" updates get propagated to prod.  

We compensated for our lack of ability to reason about what Drupal will do in response to updates, via rigor in the workflows and CI.
